/**
 * 生成通用门牌 skill（skills/{id}/SKILL.md）
 */
import { readPackageMeta } from './package-meta.mjs';
import { canonicalStepId } from './catalog.mjs';

/**
 * @param {string} value
 */
function escapeYaml(value) {
  if (/[:#{}[\],&*?|>!%@`]/.test(value) || value.includes('\n')) {
    return JSON.stringify(value);
  }
  return value;
}

/**
 * routing scope 门牌在宿主里的 scope 文案（af 与 af-explore 不同）
 * @param {import('./catalog.mjs').CatalogEntry} entry
 */
function routingScopeLabel(entry) {
  if (entry.id === 'af') return '万能自动路由（非 flow 步）';
  if (entry.id === 'af-explore') return '探索支路（非 flow 步）';
  return '路由（非 flow 步）';
}

/**
 * 门牌 description：宿主靠此自动选用；也支持 /{id} 手触
 * @param {import('./catalog.mjs').CatalogEntry} entry
 */
function doorplateDescription(entry) {
  const prefix = entry.prefix || `/${entry.id}`;
  const scopeLabel = {
    flow: 'flow 步',
    alias: `flow 步 ${canonicalStepId(entry)} 别名`,
    quick: '快捷轨（非 flow 步）',
    'pre-flow': '前置（非 flow 步）',
    routing: routingScopeLabel(entry),
  }[entry.scope] || 'flow 步';
  let desc = `AgileFlow ${entry.description}（${scopeLabel}）。触发：${prefix}、选用 ${entry.id} skill、或用户点名该步。`;
  if (entry.gate && (entry.scope === 'flow' || entry.scope === 'alias' || entry.scope === 'pre-flow')) {
    desc += ` 闸门：${entry.gate}。`;
  }
  return desc;
}

/**
 * @param {import('./catalog.mjs').CatalogEntry} entry
 * @param {string} body
 * @param {string} [version]
 */
export function renderDoorplateSkill(entry, body, version) {
  const ver = version || readPackageMeta().version;
  return `---
name: ${entry.id}
description: ${escapeYaml(doorplateDescription(entry))}
---

<!-- generated by @agileflow/cli v${ver}；勿手改；改源在 cli/workflows -->

${body.trim()}
`;
}

export const GENERATED_MARK = 'generated by @agileflow/cli';
