#!/usr/bin/env node
/**
 * CLI init / update / prune 冒烟
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const bin = path.join(__dirname, '..', 'bin', 'agileflow.mjs');

function run(args, cwd) {
  const r = spawnSync(process.execPath, [bin, ...args], {
    cwd,
    encoding: 'utf8',
    env: process.env,
  });
  return r;
}

function assert(cond, msg) {
  if (!cond) {
    console.error('FAIL', msg);
    process.exit(1);
  }
  console.log('ok  ', msg);
}

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'af-cli-'));
console.log('tmp', tmp);

// 模拟老 skill
fs.mkdirSync(path.join(tmp, '.cursor', 'skills', 'agileflow'), { recursive: true });
fs.writeFileSync(path.join(tmp, '.cursor', 'skills', 'agileflow', 'OLD.txt'), 'old');

let r = run(['--help'], tmp);
assert(r.status === 0, 'help exit 0');
assert((r.stdout || '').includes('@agileflow/cli'), 'help 含包名');
assert((r.stdout || '').includes('--step-skills-only'), 'help 含 step-skills-only');
assert((r.stdout || '').includes('run abandon'), 'help 含 run abandon');

assert((r.stdout || '').includes('无 --root'), 'help 说明无 root 为 user init');

// 用户级 init（隔离 HOME）
const fakeHome = path.join(tmp, 'fakehome');
fs.mkdirSync(fakeHome, { recursive: true });
r = spawnSync(process.execPath, [bin, 'init', '--force'], {
  cwd: tmp,
  encoding: 'utf8',
  env: { ...process.env, HOME: fakeHome, USERPROFILE: fakeHome },
});
if (r.status !== 0) {
  console.error('user init stdout', r.stdout);
  console.error('user init stderr', r.stderr);
}
assert(r.status === 0, 'user init exit 0');
assert(fs.existsSync(path.join(fakeHome, '.cursor', 'skills', 'agileflow', 'SKILL.md')), 'user cursor skill');
assert(fs.existsSync(path.join(fakeHome, '.agents', 'skills', 'af-dev', 'SKILL.md')), 'user codex doorplate');
assert(fs.existsSync(path.join(fakeHome, '.qoder', 'skills', 'agileflow', 'SKILL.md')), 'user qoder skill');
assert(!fs.existsSync(path.join(tmp, 'atlas', 'agileflow-cli.json')), 'user init 不写项目 cli.json');

// 项目级 init
r = run(['init', '--tools', 'cursor,claude,codex,workbuddy,qoder', '--root', tmp, '--force'], tmp);
if (r.status !== 0) {
  console.error('init stdout', r.stdout);
  console.error('init stderr', r.stderr);
  console.error('init error', r.error);
}
assert(r.status === 0, 'project init exit 0');
assert(fs.existsSync(path.join(tmp, '.cursor', 'skills', 'af-req', 'SKILL.md')), 'cursor af-req SKILL.md');
assert(fs.existsSync(path.join(tmp, '.cursor', 'skills', 'af', 'SKILL.md')), 'cursor af default router SKILL.md');
assert(fs.existsSync(path.join(tmp, '.cursor', 'skills', 'agileflow', 'SKILL.md')), 'cursor agileflow skill');
assert(fs.existsSync(path.join(tmp, '.cursor', 'skills', 'agileflow', 'scripts', 'validate-atlas.mjs')), 'validate script');
assert(!fs.existsSync(path.join(tmp, '.cursor', 'commands', 'af-req.md')), '无 legacy cursor command');
assert(fs.existsSync(path.join(tmp, '.claude', 'skills', 'af-req', 'SKILL.md')), 'claude af-req SKILL.md');
assert(fs.existsSync(path.join(tmp, '.agents', 'skills', 'af-dev', 'SKILL.md')), 'codex af-dev SKILL.md (.agents/skills)');
assert(!fs.existsSync(path.join(tmp, '.codex', 'skills', 'af-dev', 'SKILL.md')), 'codex 不写 .codex/skills');
assert(fs.existsSync(path.join(tmp, '.codebuddy', 'skills', 'af-fix', 'SKILL.md')), 'workbuddy af-fix SKILL.md');
assert(fs.existsSync(path.join(tmp, '.qoder', 'skills', 'af-req', 'SKILL.md')), 'qoder af-req SKILL.md');
assert(fs.existsSync(path.join(tmp, '.qoder', 'skills', 'agileflow', 'SKILL.md')), 'qoder agileflow skill');
assert(fs.existsSync(path.join(tmp, 'atlas', 'agileflow-cli.json')), 'cli.json');

const cliJson = JSON.parse(fs.readFileSync(path.join(tmp, 'atlas', 'agileflow-cli.json'), 'utf8'));
assert(cliJson.delivery === 'skills', 'delivery=skills');

const reqBody = fs.readFileSync(path.join(tmp, '.cursor', 'skills', 'af-req', 'SKILL.md'), 'utf8');
assert(reqBody.includes('generated by @agileflow/cli'), 'generated mark');
assert(reqBody.includes('name: af-req'), 'frontmatter name');
assert(reqBody.includes('req-confirm'), 'req-confirm');
assert(reqBody.includes('/af-req'), 'body 含 /af-req');
assert(reqBody.includes('agileflow'), '引用 agileflow skill');
assert(!/手打 `req:/.test(reqBody) && !reqBody.includes('等同 req:'), '无旧 req: 门牌教法');
assert(reqBody.includes('flow.yaml'), 'flow 门牌含 flow.yaml');
assert(reqBody.includes('stepId=`af-req`') || reqBody.includes('stepId=af-req'), 'flow 门牌含 stepId');

const fixBody = fs.readFileSync(path.join(tmp, '.codebuddy', 'skills', 'af-fix', 'SKILL.md'), 'utf8');
assert(fixBody.includes('非 flow 步') || fixBody.includes('快捷'), 'quick 门牌声明非 flow');
assert(!fixBody.includes('agileflow-dispatch.json'), 'quick 无台账');
assert(!fixBody.includes('write-code'), 'quick 无 write-code');

const afBody = fs.readFileSync(path.join(tmp, '.cursor', 'skills', 'af', 'SKILL.md'), 'utf8');
assert(afBody.includes('自动路由') || afBody.includes('万能'), 'af 门牌声明自动路由');
assert(!afBody.includes('探索支路（非 flow 步）'), 'af 门牌 description 不应标为探索支路');
assert(afBody.includes('非 flow') || afBody.includes('非 flow 步'), 'af 门牌非 flow');
assert(afBody.includes('禁止') && afBody.includes('AF_STEP=af'), 'af 门牌禁止写 AF_STEP=af');
assert(afBody.includes('skill 根'), 'af 门牌含 skill 根定位');
assert(afBody.includes('agileflow skill 根'), 'af 门牌 Read 指向 skill 根');
assert(!afBody.includes('Read 项目内 **agileflow** skill'), 'af 门牌不再写「项目内」误导路径');
assert(cliJson.scopes?.af?.scope === 'routing', 'cli.json scopes af routing');

const qoderAf = fs.readFileSync(path.join(tmp, '.qoder', 'skills', 'af', 'SKILL.md'), 'utf8');
assert(qoderAf.includes('同级') && qoderAf.includes('agileflow'), 'qoder af 门牌说明同级 agileflow');

const testsBody = fs.readFileSync(path.join(tmp, '.cursor', 'skills', 'af-tests', 'SKILL.md'), 'utf8');
assert(testsBody.includes('af-test'), 'af-tests alias 指向 af-test');
assert(testsBody.includes('stepId=`af-test`') || testsBody.includes('stepId=af-test'), 'af-tests 台账用 af-test');

assert(cliJson.scopes?.['af-fix']?.scope === 'quick', 'cli.json scopes quick');
assert(cliJson.scopes?.['af-req']?.scope === 'flow', 'cli.json scopes flow');
assert(cliJson.scopes?.['af-tests']?.aliasOf === 'af-test', 'cli.json af-tests aliasOf');

r = run(['gate', '--list-gates', '--root', tmp], tmp);
assert(r.status === 0, 'gate --list-gates');

r = run(['gate', 'write-code', '--root', tmp], tmp);
assert(r.status !== 0, 'gate 位置参数 write-code 能转发（无 atlas 期望非 0）');
assert((r.stdout || r.stderr || '').includes('write-code') || (r.stdout || '').includes('闸门'), 'gate 位置参数命中 write-code');

r = run(['init', '--root'], tmp);
assert(r.status === 1, 'bare --root 拒绝');
assert((r.stderr || '').includes('--root 需要路径参数'), 'bare --root 提示');

r = run(['--list-gates', '--root'], tmp);
assert(r.status === 1, '透传 bare --root 拒绝');

// 非法 flow id 不落盘门牌 skill
const evilFlow = path.join(tmp, 'atlas', 'flow.yaml');
fs.mkdirSync(path.dirname(evilFlow), { recursive: true });
fs.writeFileSync(
  evilFlow,
  `version: 1
steps:
  - id: ../evil
    mode: strict
    prompt: null
    depends: []
    outputs: []
  - id: af-req
    mode: strict
    prompt: req
    depends: []
    outputs:
      - atlas/requirements/
`,
  'utf8',
);
r = run(['update', '--step-skills-only', '--root', tmp], tmp);
assert(r.status === 0, '非法 id 时 update 仍成功（跳过）');
assert(!fs.existsSync(path.join(tmp, '.cursor', 'skills', 'af-../evil', 'SKILL.md')), '无路径穿越门牌');
assert(
  !fs.readdirSync(path.join(tmp, '.cursor', 'skills')).some((n) => n.includes('evil')),
  '无 evil 门牌目录',
);

// 自定义 flow + step-skills-only
const flowPath = path.join(tmp, 'atlas', 'flow.yaml');
fs.writeFileSync(
  flowPath,
  `version: 1
steps:
  - id: af-research
    mode: strict
    prompt: null
    depends: []
    outputs:
      - atlas/logs/research.md
  - id: af-req
    mode: strict
    prompt: req
    depends: []
    outputs:
      - atlas/requirements/
`,
  'utf8',
);

r = run(['update', '--step-skills-only', '--root', tmp], tmp);
assert(r.status === 0, 'update --step-skills-only');
assert(fs.existsSync(path.join(tmp, '.cursor', 'skills', 'af-research', 'SKILL.md')), 'af-research 生成');

// --commands-only 别名仍可用
r = run(['update', '--commands-only', '--root', tmp], tmp);
assert(r.status === 0, 'update --commands-only alias');
assert((r.stderr || '').includes('弃用') || (r.stdout || '').includes('弃用'), 'commands-only deprecation warn');

// 去掉 research
fs.writeFileSync(
  flowPath,
  `version: 1
steps:
  - id: af-req
    mode: strict
    prompt: req
    depends: []
    outputs:
      - atlas/requirements/
`,
  'utf8',
);
r = run(['update', '--step-skills-only', '--root', tmp], tmp);
assert(r.status === 0, 'update prune');
assert(!fs.existsSync(path.join(tmp, '.cursor', 'skills', 'af-research', 'SKILL.md')), 'af-research 已删');

// 旧 command 迁移清理
const legacyCmd = path.join(tmp, '.cursor', 'commands', 'af-req.md');
fs.mkdirSync(path.dirname(legacyCmd), { recursive: true });
fs.writeFileSync(legacyCmd, '<!-- generated by @agileflow/cli v9 -->\nlegacy', 'utf8');
r = run(['update', '--root', tmp], tmp);
assert(r.status === 0, 'update 清理 legacy command');
assert(!fs.existsSync(legacyCmd), 'legacy command 已删');

console.log('\nall cli tests passed');
